# Generated by Django 5.2 on 2025-06-07 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0004_task_done'),
        ('workspace', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='task',
            unique_together={('workspace', 'title')},
        ),
    ]
