# Generated by Django 5.2 on 2025-06-06 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0003_remove_board_description_remove_board_height_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='cards'),
        ),
    ]
