# Generated by Django 5.2 on 2025-06-07 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0004_card_attachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='done',
            field=models.BooleanField(default=False),
        ),
    ]
